server:
  port: 80
spring:
#  mail:
#    host: smtp.qq.com
#    username: 326981317@qq.com
#    password: gzromwxiwvusbhbb
#    default-encoding: utf-8
#  rabbitmq:
#    host: 192.168.19.128
#    port: 5672
#    username: admin
#    password: admin
#    publisher-confirm-type: correlated
#    publisher-returns: true
#  redis:
#    host: localhost
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: daiwenxiang
    hikari:
      maximum-pool-size: 200
      minimum-idle: 10
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd
mybatis:
#  type-aliases-package: xxxxxxxxxxxxxxx.entity
#  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
#pagehelper:
#  reasonable: true